name: Node CI

on:
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install, build, test
        run: |
          npm ci
          npm run build
          npm test
        env:
          CI: true


  CheckCodestyle:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Check codestyle
        run: |
          npm install
          npm run lint
        env:
          CI: true


  BuildAndDeploy:
    needs: CheckCodestyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Deploy
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRPO_1EFE3 }}'
          channelId: live
          projectId: trpo-1efe3
