name: Node CI

on:
  push:
    branches:
      - master

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install, build, test
        run: |
          npm install
          npm run build
          npm test
        env:
          CI: true


  checkCodestyle:
    needs: buildAndTest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install and check codestyle
        run: |
          npm install
          npm run lint
        env:
          CI: true


  build_and_deploy:
    needs: checkCodestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRPO_1EFE3 }}'
          channelId: live
          projectId: trpo-1efe3
